### ISSUE TITLE
Simplify Factory to delegate GitHub work to agents

### ISSUE THREAD

**Issue by owainlewis** [owainlewis/machinist#48]
## Outcome

Factory reliably detects, claims, isolates, and supervises work, then delegates the complete adaptive GitHub and engineering workflow to the agent.

## Acceptance criteria

- Remove the effect-scoped GitHub command layer introduced by #40.
- Workflows do not require proposal or delivery effect declarations.
- Ticket tasks give the agent the repository, issue number, worktree, and workflow prompt, and instruct it to fetch live issue context with `gh`.
- Scheduled tasks may use authenticated `gh` directly for the workflow outcome.
- Agents may comment, label, push the Factory branch, open or update draft PRs, and handle CI using normal tools.
- Factory keeps deterministic polling, deduplication, trusted approval, durable claims, worktree ownership, concurrency, supervision, recovery, and human-only merge policy.
- Factory does not implement a provider command surface or deterministic PR pipeline.
- Existing daemon, approval, worktree, recovery, and inspection tests remain green.

## Checks

```sh
cargo fmt --all --check
cargo clippy --all-targets --all-features -- -D warnings
cargo test --all-targets
```

## Out of scope

Credential isolation and automatic merge.
